-- Your SQL goes here
CREATE TABLE shouts (
    id SERIAL PRIMARY KEY,
    author_id INTEGER NOT NULL REFERENCES players (id) ON DELETE CASCADE,
    song_id INTEGER NOT NULL REFERENCES songs (id) ON DELETE CASCADE,
    posted_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content VARCHAR(240) NOT NULL
);