//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::rivalry::Entity as Rivalry;
pub use super::score::Entity as Score;
pub use super::shout::Entity as Shout;
pub use super::song::Entity as Song;
pub use super::player::Entity as Player;
