//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "_friends")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub a: i32,
    #[sea_orm(primary_key)]
    pub b: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::A",
        to = "super::player::Column::Id",
    )]
    Player2,
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::B",
        to = "super::player::Column::Id",
    )]
    Player1,
}

impl ActiveModelBehavior for ActiveModel {}
