name: Build and publish container image

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ${{ matrix.os }}
    environment: Container deploy
    permissions:
        contents: read
        packages: write
        id-token: write
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        arch: [linux/amd64, linux/arm64]
        exclude:
          - os: ubuntu-latest
            arch: linux/arm64
          - os: ubuntu-24.04-arm
            arch: linux/amd64

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Build and push Docker image
          id: push
          uses: docker/build-push-action@v6
          with:
            platforms: ${{ matrix.arch }}
            context: .
            provenance: false
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha,mode=max

        - shell: bash
          env:
            WATCHTOWER_URL: ${{ secrets.WATCHTOWER_URL }}
            WATCHTOWER_KEY: ${{ secrets.WATCHTOWER_KEY }}
          run: |
            curl -H "Authorization: Bearer $WATCHTOWER_KEY" $WATCHTOWER_URL
